In [1]:
#pip install us

In [2]:
#pip install geopandas

In [3]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states


#import gmaps

# Census & gmaps API Keys
from config import api_key
c = Census(api_key, year=2019)

# Configure gmaps
#gmaps.configure(api_key=gkey)

In [4]:
# Run Census Search to retrieve data on all states
# Note the addition of "B23025_005E" for unemployment count
census_data = c.acs5.state_county_tract(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E",
                          "B23025_005E",
                          "B08136_003E",
                          "B23025_004E",
                          "B23025_005E",
                          "B15003_017E"), 
                         state_fips = states.MD.fips,
                         county_fips = "*",
                         tract = "*")

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)
census_pd.head()

,NAME,B19013_001E,B01003_001E,B01002_001E,B19301_001E,B17001_002E,B23025_005E,B08136_003E,B23025_004E,B15003_017E,state,county,tract
0,"Census Tract 10.02, Washington County, Maryland",69083.0,3857.0,44.0,32222.0,353.0,81.0,NaN,2174.0,895.0,24,043,001002
1,"Census Tract 101, Washington County, Maryland",62500.0,910.0,41.0,30044.0,166.0,17.0,NaN,501.0,255.0,24,043,010100
2,"Census Tract 112.02, Washington County, Maryland",68984.0,4613.0,36.9,29683.0,471.0,107.0,NaN,2006.0,933.0,24,043,011202
3,"Census Tract 5, Washington County, Maryland",39317.0,5732.0,32.2,21302.0,1739.0,216.0,NaN,2353.0,1428.0,24,043,000500
4,"Census Tract 104, Washington County, Maryland",64099.0,7853.0,37.4,27705.0,965.0,237.0,NaN,3480.0,1691.0,24,043,010400

In [5]:

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B08136_003E": "Time spent commuting (minutes)",
                                      "B23025_004E": "Number of Employed, age 16+",
                                      "B23025_005E": "Unemployment Count",
                                      "B15003_017E": "Number of persons age 25+ graduated high school",
                                      "NAME": "Name", "state": "State"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Add in Employment Rate (Employment Count / Population)
census_pd["Unemployment Rate"] = 100 * \
    census_pd["Unemployment Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["State", "Name", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "Poverty Rate", "Unemployment Rate", 
                       "Time spent commuting (minutes)","Number of Employed, age 16+", "Unemployment Count",
                      "Number of persons age 25+ graduated high school"]]

census_pd.head()

,State,Name,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Unemployment Rate,Time spent commuting (minutes),"Number of Employed, age 16+",Unemployment Count,Number of persons age 25+ graduated high school
0,24,"Census Tract 10.02, Washington County, Maryland",3857.0,44.0,69083.0,32222.0,353.0,9.152191,2.100078,NaN,2174.0,81.0,895.0
1,24,"Census Tract 101, Washington County, Maryland",910.0,41.0,62500.0,30044.0,166.0,18.241758,1.868132,NaN,501.0,17.0,255.0
2,24,"Census Tract 112.02, Washington County, Maryland",4613.0,36.9,68984.0,29683.0,471.0,10.210275,2.319532,NaN,2006.0,107.0,933.0
3,24,"Census Tract 5, Washington County, Maryland",5732.0,32.2,39317.0,21302.0,1739.0,30.338451,3.768318,NaN,2353.0,216.0,1428.0
4,24,"Census Tract 104, Washington County, Maryland",7853.0,37.4,64099.0,27705.0,965.0,12.288297,3.017955,NaN,3480.0,237.0,1691.0

In [6]:
census_pd["Poverty Rate"] = census_pd["Poverty Rate"].astype(float).round(1)
census_pd.head()

,State,Name,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Unemployment Rate,Time spent commuting (minutes),"Number of Employed, age 16+",Unemployment Count,Number of persons age 25+ graduated high school
0,24,"Census Tract 10.02, Washington County, Maryland",3857.0,44.0,69083.0,32222.0,353.0,9.2,2.100078,NaN,2174.0,81.0,895.0
1,24,"Census Tract 101, Washington County, Maryland",910.0,41.0,62500.0,30044.0,166.0,18.2,1.868132,NaN,501.0,17.0,255.0
2,24,"Census Tract 112.02, Washington County, Maryland",4613.0,36.9,68984.0,29683.0,471.0,10.2,2.319532,NaN,2006.0,107.0,933.0
3,24,"Census Tract 5, Washington County, Maryland",5732.0,32.2,39317.0,21302.0,1739.0,30.3,3.768318,NaN,2353.0,216.0,1428.0
4,24,"Census Tract 104, Washington County, Maryland",7853.0,37.4,64099.0,27705.0,965.0,12.3,3.017955,NaN,3480.0,237.0,1691.0

In [7]:
census_pd["Unemployment Rate"] = census_pd["Unemployment Rate"].astype(float).round(1)
census_pd.head()

,State,Name,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Unemployment Rate,Time spent commuting (minutes),"Number of Employed, age 16+",Unemployment Count,Number of persons age 25+ graduated high school
0,24,"Census Tract 10.02, Washington County, Maryland",3857.0,44.0,69083.0,32222.0,353.0,9.2,2.1,NaN,2174.0,81.0,895.0
1,24,"Census Tract 101, Washington County, Maryland",910.0,41.0,62500.0,30044.0,166.0,18.2,1.9,NaN,501.0,17.0,255.0
2,24,"Census Tract 112.02, Washington County, Maryland",4613.0,36.9,68984.0,29683.0,471.0,10.2,2.3,NaN,2006.0,107.0,933.0
3,24,"Census Tract 5, Washington County, Maryland",5732.0,32.2,39317.0,21302.0,1739.0,30.3,3.8,NaN,2353.0,216.0,1428.0
4,24,"Census Tract 104, Washington County, Maryland",7853.0,37.4,64099.0,27705.0,965.0,12.3,3.0,NaN,3480.0,237.0,1691.0

AttributeError: 'DataFrame' object has no attribute 'type'